# Generated by Django 2.2 on 2019-09-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitebricks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='pg',
        ),
    ]
