# Generated by Django 2.2 on 2019-09-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebricks', '0002_remove_image_pg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='pg',
            name='image',
            field=models.FileField(null=True, upload_to='media/uploads'),
        ),
    ]
