# Generated by Django 2.2 on 2019-09-06 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitebricks', '0003_auto_20190904_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='userinfo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='whitebricks.Userinfo'),
        ),
    ]
