# Generated by Django 2.2 on 2019-09-06 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whitebricks', '0004_pg_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pg',
            name='userinfo',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='whitebricks.Userinfo'),
        ),
    ]
