# Generated by Django 2.2 on 2019-09-06 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitebricks', '0005_auto_20190906_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg',
            name='userinfo',
        ),
    ]
