# Generated by Django 2.2 on 2019-09-16 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitebricks', '0008_pg_publisher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg',
            name='publisher',
        ),
    ]
