# Generated by Django 2.2 on 2019-09-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitebricks', '0012_pg_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pg',
            name='added_by',
        ),
    ]
