# Generated by Django 2.2 on 2019-09-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whitebricks', '0013_remove_pg_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='pg',
            name='created_by',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
