# Generated by Django 2.2 on 2019-10-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whitebricks', '0015_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
